apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-ingress.configName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
{{- if .Values.controller.config.annotations }}
  annotations:
{{ toYaml .Values.controller.config.annotations | indent 4 }}
{{- end }}
data:
{{- if .Values.tcpLoadBalancingRules.rules }}
  stream-snippets: | 
    {{- range $rule := .Values.tcpLoadBalancingRules.rules }}
            upstream {{ $rule.serviceName }}-tcp { 
              server {{ $rule.serviceName }}:{{ $rule.port }};
            }
            server {
              listen {{ $rule.port }};
              proxy_pass {{ $rule.serviceName }}-tcp;
            }
    {{- end }}
{{- end }}

